### ISSUE TITLE
Explore NeurIPS '23 challenge.

### ISSUE THREAD

**Issue by breezykermo** [breezykermo/iris#21]
- [The paper](https://arxiv.org/html/2409.17424v1) 
- [The leaderboard](https://big-ann-benchmarks.com/neurips23.html)
- [The codebase](https://github.com/harsha-simhadri/big-ann-benchmarks)

**Comment by MithiJ** [comment]
Sparse Data
I'm not sure how the sparseness of datasets will interact with either HNSW or LSH. The winner for sparse data used HNSW with a new searching framework. They used VQ which degraded accuracy + a refinement step to get more precision.

OOD Data
When the dataset is say an image representation but your query set is a text repr. Yandex Text-to-Image  10M This could be interesting and poses 2 options for semantic caching -> caching just the text queries passed in vs caching intermediate layers within HNSW
PyANNS does some adpative prefetching that gets them there

Filtered data
Being able to query on metadata such as image metadata or on arxiv, the author, publishing date, journal, etc. And then, being able to do that while also querying the actual text or image - semantic information underneath. YFCC 100M. The baseline here is based on FAISS.

The key here is metadata might be duplicated. The best performers used some way to highlight common metadata and used the metadata as the primary key on the index to search with.


Actual metrics being benchmarked

Accuracy i.e., recall : 10-recall@10 : are the top 10 closest vectors returned actually the top 10. What % of the vectors in the result are actually in the top 10?

# I'm not completely sure if changing the first or second 10 here lend to interesting result. say what % of top 50 vectors returned are in the actual top 10 nearest neighbours?

Throughput QPS -> more regarding batch processing, using multiple threads, potentially semantic caching or caching intermediate results if thats useful
Latency
These are probably most important for distribution strategies

**Comment by breezykermo** [comment]
Thanks @MithiJ, this is a good summary. Our primary aim in this ticket is to work out which databases are useful for our experiments. Which of [the datasets](https://big-ann-benchmarks.com/neurips23.html) do you propose we should use/provision at this stage?

**Comment by MithiJ** [comment]
Each of these tracks has its own dataset and query set so I think once we decide what tracks to try out, we can just pick off their datasets (like Yandex for OOD data or YFCC for filtered data/metadata). One thing is that I believe none of these are billion scale. 2021 focused on billion scale datasets but this time, to democratize the playing field, they had everyone use the same hardware and less consuming datasets. If our project still focuses more on distribution, it might be best to use the billion scale datasets and use a small snippet of these (either 10M or 100M) to understand performance under different characteristics of workloads.
